# Use the file format compatible with Docker Compose 3.8
version: "3.3"

services:
  sales-management-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "cd src && python main.py"
    depends_on:
      - db
    volumes:
      - ./.:/var/www/poke_trader_calculator
      - "/etc/localtime:/etc/localtime:ro"
      - .:/code:cached
    environment:
      dsadaopk: development
  db:
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"

volumes:
  db_data: